#!/usr/bin/expect
# Copyright 2017 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Tests for libvecpf
#

source ./shared.exp

set rc 0

set CC [compiler_path]
set CFLAGS "-O2 -Wall -Wno-format -maltivec"
set STATIC_LIBS "-Wl,-u,__libvecpf_init -lvecpf -lm"
set LIBS "-lvecpf"

if { [array names env -exact "AT_LIBVECPF_VER"] == "" } {
	printit "WARNING: libvecpf is not configured in the config file."
	printit "Skipping..."
	exit ${ENOSYS}
}

#
# Check if AT is able to build and link against libvecpf libraries
# This test checks for important headers and both static and dynamic libs
#
set tmp_file [exec mktemp]

if { $TARGET32 } {
	printit "Testing target 32 linking..."
	compile "${CC} -m32 -static ${CFLAGS} ${FULLPATH}/test.c ${STATIC_LIBS} -o ${tmp_file}"
	compile "${CC} -m32 ${CFLAGS} ${FULLPATH}/test.c ${LIBS} -o ${tmp_file}"
	printit "Successfully built 32 bit static and dynamic executables"
}
if { $TARGET64 } {
	printit "Testing target 64 linking..."
	compile "${CC} -m64 -static ${CFLAGS} ${FULLPATH}/test.c ${STATIC_LIBS} -o ${tmp_file}"
	compile "${CC} -m64 ${CFLAGS} ${FULLPATH}/test.c ${LIBS} -o ${tmp_file}"
	printit "Successfully built 64 bit static and dynamic executables"
}

file delete -force ${tmp_file}
