#!/usr/bin/expect
# Copyright 2019 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Tests for pveclib
#

source ./shared.exp

set rc 0

set CC [compiler_path]
set CFLAGS "-O2 -Wall -c"

if { [array names env -exact "AT_PVECLIB_VER"] == "" } {
	printit "WARNING: pveclib is not configured in the config file."
	printit "Skipping..."
	exit ${ENOSYS}
}

if { $TARGET32 } {
	printit "Skipping: pveclib is not available in 32 bits"
	exit ${ENOSYS}
}

#
# Check if pveclib headers are provided in the correct location
# Headers should be under a pveclib/ sub-directory
#
set tmp_file [exec mktemp]

printit "Testing 64 bit compilation..."
compile "${CC} -m64 ${CFLAGS} ${FULLPATH}/test.c -o ${tmp_file}"
printit "Successfully compiled with pveclib headers"

file delete -force ${tmp_file}