#!/usr/bin/expect
# Copyright 2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Check if libnxz headers are provides in the correct location, i.e.:
# under a libnxz/ sub-directory.
#

source ./shared.exp

set rc 0

set CC [compiler_path]
set CFLAGS "-O2 -Wall -c"
set LIBS "-lnxz"

if { [array names env -exact "AT_LIBNXZ_VER"] == "" } {
	printit "WARNING: libnxz is not configured in the config file."
	printit "Skipping..."
	exit ${ENOSYS}
}

if { $TARGET32 } {
	printit "WARNING: libnxz is not available in 32 bits."
	printit "Skipping..."
	exit ${ENOSYS}
}

set tmp_file [exec mktemp]

printit "Testing target 64..."
compile "${CC} -m64 ${CFLAGS} ${LIBS} ${FULLPATH}/test.c -o ${tmp_file}"
printit "Successfully built 64 bit dynamic executable"

file delete -force ${tmp_file}
