#!/usr/bin/expect
# Copyright 2017 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Tests for TBB
#

source ./shared.exp

set rc 0

set CXX [compiler_path g++]
# In TBB 2019_U9, a pragma in tbb/tbb.h warns about deprecated functions.
set CFLAGS "-O2 -Wall -DTBB_SUPPRESS_DEPRECATED_MESSAGES"
set LIBS "-ltbb -ltbbmalloc_proxy -ltbbmalloc"

if { [array names env -exact "AT_TBB_VER"] == "" } {
	printit "WARNING: TBB is not configured in the config file."
	printit "Skipping..."
	exit ${ENOSYS}
}

# Look for TBB's major and minor version.
if { $env(AT_TBB_VER) != "master" } {
	if { ! [regexp "(\[0-9\]+)\.(\[0-9\]+).*" $env(AT_TBB_VER) match major_ver minor_ver] } {
		fvtr_error "Failed to identify TBB major and minor versions from $env(AT_TBB_VER)"
	}
}

proc memtest {} {
	global TARGET32
	global TARGET64
	global CXX
	global CFLAGS
	global LIBS
	global tmp_file
	global FULLPATH

	printit "Testing malloc/free usage..."
	if { $TARGET32 } {
		printit "Testing target 32 linking..."
		compile "${CXX} -m32 ${CFLAGS} ${FULLPATH}/mem-test.cpp ${LIBS} -o ${tmp_file}"
		printit "Successfully built 32 bit dynamic executable"
	}
	if { $TARGET64 } {
		printit "Testing target 64 linking..."
		compile "${CXX} -m64 ${CFLAGS} ${FULLPATH}/mem-test.cpp ${LIBS} -o ${tmp_file}"
		printit "Successfully built 64 bit dynamic executable"
	}
}

proc parallel_test {} {
	global TARGET32
	global TARGET64
	global CXX
	global CFLAGS
	global LIBS
	global tmp_file
	global FULLPATH

	printit "Testing parallel execution..."
	if { $TARGET32 } {
		printit "Testing target 32 linking..."
		compile "${CXX} -m32 ${CFLAGS} ${FULLPATH}/par-test.cpp ${LIBS} -o ${tmp_file}"
		printit "Successfully built 32 bit dynamic executable"
	}
	if { $TARGET64 } {
		printit "Testing target 64 linking..."
		compile "${CXX} -m64 ${CFLAGS} ${FULLPATH}/par-test.cpp ${LIBS} -o ${tmp_file}"
		printit "Successfully built 64 bit dynamic executable"
	}
}

#
# Check if AT is able to build and link against TBB libraries
# This test checks for important headers and dynamic libs
#
set tmp_file [exec mktemp]

# Run memtest for all TBB versions.
memtest

# Prior to 4.2u4 we would need different headers,
# so parallel_test is supported by TBB >= 4.3 only.
if { ($env(AT_TBB_VER) == "master") || (${major_ver} >= 4 && ${minor_ver} >= 3) } {
	parallel_test
}

file delete -force ${tmp_file}
