#!/bin/bash
#
# Copyright 2017 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Minimal lsb_release that is able to provide the functionality required by
# the AT build framework.
# It was developed as workaround in a distro that didn't have lsb_release
# working by the time we started using it.

REL_F="/etc/*release"

dist_id ()
{
	echo -ne "Distributor ID:\t"
	grep "^NAME=" ${REL_F} | sed 's/^.*=\(.*\)$/\1/'
}

release ()
{
	echo -ne "Release:\t"
	grep "^VERSION_ID=" ${REL_F} | sed 's/^.*=\(.*\)$/\1/'
}

case ${1} in
	"-i")
		dist_id
		;;
	"-r")
		release
		;;
esac
