#!/bin/bash
#
# Copyright 2017 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Set up a wrapper script that generates by default the kind of code we
# need.  It calls the gcc found from PATH.  This is only needed if the
# kind of binary we're building is different from that build by default
# by gcc in the path, e.g. if we're building 64-bit gcc binaries from
# a gcc that defaults to 32-bit binaries.

# Usage: BUILD_CC=<path>/gcc64 when configuring GCC with --with-cpu=default64

#_CC=`echo $0 | sed -e 's#.*/##'`
_CC=${0##*/}
_cmd="${_CC%%[0-9]*}"
_arch="-m${_CC##$_cmd}"  # Default -m[32|64] value unless overridden by the user."
for opt in "${@}"; do
	case "${opt}" in
		-m32)
			_arch=""
			break;;
		-m64)
			_arch=""
			break;;
	esac
done
exec ${_cmd} ${_arch} "${@}"

