#!/usr/bin/expect
# Copyright 2017 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Tests for gold linker
#

source ./shared.exp

set rc 0

set CC [compiler_path]
set CFLAGS "-O2 -Wall"
set LIBS "-lm"

#
# Check if binutils has been configured to build the gold linker
# Gold is enabled by passing the --enable-gold when building binutils
# This test checks if the -fuse-ld=gold option works
#
set tmp_file [exec mktemp]

if { $TARGET32 } {
	printit "Testing 32 bit gold linking..."
	compile "${CC} -m32 ${CFLAGS} -mbss-plt -fuse-ld=gold ${FULLPATH}/test.c ${LIBS} -o ${tmp_file}"
	printit "Successfully built and linked 32 bit with gold"
}
if { $TARGET64 } {
	printit "Testing 64 bit gold linking..."
	compile "${CC} -m64 ${CFLAGS} -fuse-ld=gold ${FULLPATH}/test.c ${LIBS} -o ${tmp_file}"
	printit "Successfully built and linked 64 bit with gold"
}

file delete -force ${tmp_file}
