#!/usr/bin/expect
# Copyright 2017 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Check if AT provides headers and static libraries for libexpat.
# Test only for 64-bit versions as AT doesn't provide 32-bit.
#

source ./shared.exp

set rc 0

set CC [compiler_path]
set CFLAGS "-O2 -Wall"
set LIBS "-lexpat"

# libexpat isn't available in cross compilers
if { $env(AT_CROSS_BUILD) == "yes" } {
	printit "Skipping libexpat tests: this is a cross compiler"
	exit ${ENOSYS}
}

#
# Check if AT is able to build and link against libexpat libraries
# This test checks for important headers and static libs
#
set tmp_file [exec mktemp]

printit "Testing target 64 linking..."
compile "${CC} -m64 -static ${CFLAGS} ${FULLPATH}/test.c ${LIBS} -o ${tmp_file}"
printit "Successfully built 64 bit static executable"

file delete -force ${tmp_file}
